### ISSUE TITLE
PlaceHolderAPI Hook Depricated

### ISSUE THREAD

**Issue by BrettPlays** [SubSide/KOTH#130]
Read here for more info: https://www.spigotmc.org/resources/placeholderapi.6245/updates
In short, the method you are using to hook into placeholderapi will be deprecated soon so please update it.

**Comment by Kurt6** [comment]
Just got the message as well, [PlaceholderAPI] KoTH is currently using a deprecated method to hook into PlaceholderAPI. Placeholders for that plugin no longer work. Please consult [SubSide] and urge them to update it ASAP. 

ASAP boss :)

**Comment by SubSide** [comment]
So I took a long break on this project... :p

But I'm feeling pretty exciting to take on this project once more and get all the issues that are being found sorted out!

**Comment by opd02** [comment]
@SubSide Did you edit the way you hook into Placeholder? Because I get this error when I try and start with placeholder installed and KoTH.
`18.12 04:05:00 [Server] ERROR Error occurred while enabling KoTH v1.5.1 (Is it up to date?)
18.12 04:05:00 [Server] INFO java.lang.NoClassDefFoundError: subside/plugins/koth/hooks/PlaceholderAPIHook
18.12 04:05:00 [Server] INFO at subside.plugins.koth.hooks.HookManager.onEnable(HookManager.java:32) ~[?:?]
18.12 04:05:00 [Server] INFO at subside.plugins.koth.KothPlugin.trigger(KothPlugin.java:137) ~[?:?]`
