### ISSUE TITLE
paper spigot 1.12.2

### ISSUE THREAD

**Issue by Freddereck** [SubSide/KOTH#143]
[04:34:49 INFO]: [KoTH] Enabling KoTH v1.5.1
[04:34:49 INFO]: [KoTH] VanishNoPacket hook: Disabled
[04:34:49 INFO]: [KoTH] Featherboard hook: Disabled
[04:34:49 INFO]: [KoTH] Bossbar hook: Disabled
[04:34:49 INFO]: [KoTH] PvPManager hook: Disabled
[04:34:49 ERROR]: Error occurred while enabling KoTH v1.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/ess3/api/IEssentials
 at subside.plugins.koth.hooks.HookManager.onEnable(HookManager.java:29) ~[?:?]
 at subside.plugins.koth.KothPlugin.trigger(KothPlugin.java:137) ~[?:?]
 at subside.plugins.koth.KothPlugin.onEnable(KothPlugin.java:116) ~[?:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
 at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
 at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
 at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
 at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: net.ess3.api.IEssentials
 at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
 ... 14 more

**Comment by CoronaCarrot** [comment]
im having same issue

**Comment by sjander12** [comment]
same thing
