### ISSUE TITLE
Error PlayerJoinEvent & PlayerQuitEvent

### ISSUE THREAD

**Issue by dartasen** [SubSide/KOTH#69]
I have previously report this error on spigot thread but you seem to ignore it.

In your last updates of KoTH, there are many error when players leave or join the server.

` [Server thread/ERROR]: Could not pass event PlayerJoinEvent to KoTH v1.4.8
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-38ddb34-c19c293]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-38ddb34-c19c293]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-38ddb34-c19c293]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: be/maximvdw/featherboard/api/FeatherBoardAPI
    at subside.plugins.koth.hooks.FeatherboardHook.entersRange(FeatherboardHook.java:35) ~[?:?]
    at subside.plugins.koth.hooks.AbstractRangeHook.addPlayer(AbstractRangeHook.java:192) ~[?:?]
    at subside.plugins.koth.hooks.AbstractRangeHook.updatePlayer(AbstractRangeHook.java:225) ~[?:?]
    at subside.plugins.koth.hooks.AbstractRangeHook.onPlayerJoin(AbstractRangeHook.java:133) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor519.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-38ddb34-c19c293]
    ... 14 more`
`[Server thread/ERROR]: Could not pass event PlayerQuitEvent to KoTH v1.4.8 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-38ddb34-c19c293] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-38ddb34-c19c293] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-38ddb34-c19c293] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1064) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:316) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:174) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-38ddb34-c19c293] at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-38ddb34-c19c293] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101] Caused by: java.lang.NoClassDefFoundError: be/maximvdw/featherboard/api/FeatherBoardAPI at subside.plugins.koth.hooks.FeatherboardHook.leavesRange(FeatherboardHook.java:52) ~[?:?] at subside.plugins.koth.hooks.AbstractRangeHook.removePlayer(AbstractRangeHook.java:203) ~[?:?] at subside.plugins.koth.hooks.AbstractRangeHook.onPlayerQuit(AbstractRangeHook.java:143) ~[?:?] at sun.reflect.GeneratedMethodAccessor722.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-38ddb34-c19c293] ... 12 more `

Please fix it quickly

**Comment by SubSide** [comment]
Oh sorry if I didn't respond! I try to respond to everyone but sadly sometimes (rarely actually) a comment slips through.

Do you have Featherboard installed on your server?

**Comment by dartasen** [comment]
Nop, I don't use Featherboard, only Vanilla's scoreboard

**Comment by SubSide** [comment]
Is the Featherboard hook in the config disabled?

**Comment by dartasen** [comment]
Oh, the option seems to have been reset with the last updates...
I changed that and I haven't error anymore!
Sorry for inconvenience.

**Comment by SubSide** [comment]
Glad I could help ^^
