### ISSUE TITLE
Probleme with KOTH2FactionOne addon

### ISSUE THREAD

**Issue by snakypex** [SubSide/KOTH#72]
Hello,
I've this error when I enter in Koth zone:
[14:34:20 WARN]: java.lang.reflect.InvocationTargetException
[14:34:20 WARN]:        at sun.reflect.GeneratedConstructorAccessor140.newInstance(Unknown Source)
[14:34:20 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:34:20 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CaptureTypeRegistry.getCapper(CaptureTypeRegistry.java:181)
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CapInfo.getRandomCapper(CapInfo.java:62)
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CapInfo.findAndSetNewEntity(CapInfo.java:167)
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CapInfo.update(CapInfo.java:71)
[14:34:20 WARN]:        at subside.plugins.koth.gamemodes.KothClassic.update(KothClassic.java:125)
[14:34:20 WARN]:        at subside.plugins.koth.modules.KothHandler.run(KothHandler.java:81)
[14:34:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:34:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:34:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:34:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:34:20 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:34:20 WARN]: Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.FPlayers.getInstance()Lcom/massivecraft/factions/FPlayers;
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CappingFactionUUID.lambda$0(CappingFactionUUID.java:22)
[14:34:20 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[14:34:20 WARN]:        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[14:34:20 WARN]:        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[14:34:20 WARN]:        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[14:34:20 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:34:20 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[14:34:20 WARN]:        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[14:34:20 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:34:20 WARN]:        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
[14:34:20 WARN]:        at subside.plugins.koth.captureentities.CappingFactionUUID.<init>(CappingFactionUUID.java:24)
[14:34:20 WARN]:        ... 14 more

Best regards

**Comment by snakypex** [comment]
My version of FactionOne is FactionOne 1.2.1, it's a version to Spigot 1.8.8

**Comment by snakypex** [comment]
Plugin works !
But in the scoreboard with featherboard it's write a player's pseudo. I would like it's write a Faction's name
Thanks

**Comment by snakypex** [comment]
After restart doesn't work....
Error: 
[16:22:49 WARN]: java.lang.NoSuchMethodException: subside.plugins.koth2factionsone.CappingFactionsOne.<init>(subside.plugins.koth.captureentities.CaptureTypeRegistry, java.util.Collection)

**Comment by SubSide** [comment]
I just uploaded a new version on spigot, this should fix it :)
