### ISSUE TITLE
Trying to use the PlaceHolders

### ISSUE THREAD

**Issue by Sickness2** [SubSide/KOTH#80]
Im trying to use Featherboard with Koth and it doesnt work, whenever I start a Koth the scoreboard doesnt update.

Im using the Placeholders that are on the spigot https://www.spigotmc.org/resources/koth-king-of-the-hill-mc-1-7-to-1-12.7689/

I have PlaceHolderApi and FeatherBoard last version.

**Comment by Sickness2** [comment]
Just checked the console and FeatherBoard generated this error:
[19:30:51] [Craft Scheduler Thread - 26614/WARN]: Exception in thread "Craft Scheduler Thread - 26614" 
[19:30:51] [Craft Scheduler Thread - 26614/WARN]: org.apache.commons.lang.UnhandledException: Plugin FeatherBoard v3.18.1 generated an exception while executing task 16061
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: subside/plugins/koth/adapter/KothHandler
	at me.F64.papiexpansions.koth.ExpansionKoTH.onPlaceholderRequest(ExpansionKoTH.java:41)
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342)
	at be.maximvdw.featherboardcore.placeholders.aB$1.a(PlaceholderAPIPlaceholder.java:29)
	at be.maximvdw.featherboardcore.placeholders.aB$1.getResult(PlaceholderAPIPlaceholder.java:18)
	at be.maximvdw.featherboardcore.placeholders.Placeholder.getPlaceholders(Placeholder.java:219)
	at be.maximvdw.featherboardcore.a.d.a(AnimationStaticPart.java:49)
	at be.maximvdw.featherboardcore.a.a.a(Animation.java:157)
	at be.maximvdw.featherboardcore.a.a.a(Animation.java:47)
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart.updatePlaceholders(ScoreboardPart.java:300)
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart.access$000(ScoreboardPart.java:24)
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart$a.run(ScoreboardPart.java:286)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
